apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app-selenium-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-k8s-app-selenium
  template:
    metadata:
      labels:
        app: my-k8s-app-selenium
    spec:
      containers:
      - name: my-k8s-app-selenium
        image: jakkani7/my-k8s-app-selenium:latest  # your Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
